apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: connector-hpa
  namespace: {{.Values.namespace}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.deploymentName}}
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
